# -*- coding: utf-8 -*-
"""cnn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hURe9J5yQGbmN76PTU3iQofWc6ZoIMOq
"""

import  numpy as np
import pandas as pd
import os
import time
import tensorflow as tf
from keras.models import Sequential
from keras.layers import (Input, Embedding, SimpleRNN, Dense, Activation,
                          TimeDistributed)
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow import keras
from keras.layers import Dense
import tensorflow as tf
from tensorflow.keras.optimizers import RMSprop
import os
import cv2 as cv
from tensorflow.keras.models import Sequential
from keras.layers import Dense, Conv2D , MaxPool2D , Flatten , Dropout 
from keras.optimizers import Adam
from sklearn.metrics import classification_report,confusion_matrix
from keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input,decode_predictions
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import RocCurveDisplay
from functools import partial

x_test=np.load('/content/drive/MyDrive/x_test.npy')
x_train=np.load('/content/drive/MyDrive/x_train.npy')
y_test=np.load('/content/drive/MyDrive/y_test.npy')
y_train=np.load('/content/drive/MyDrive/y_train.npy')

x_test_generated=np.load('/content/drive/MyDrive/generated/generated_image1.npy')
y_test_generated=np.load('/content/drive/MyDrive/generated/generated_label1.npy')
xtg=x_test_generated.reshape(x_test_generated.shape[0]*x_test_generated.shape[1],128,128,3)
ytg=y_test_generated.reshape(y_test_generated.shape[0]*y_test_generated.shape[1],)
p=int(y_test.shape[0]*0.2)
q=np.random.choice(np.arange(y_test.shape[0]-1), p, replace=False)
x=[]
y=[]
for i in q:
    x.append(x_test[i])
    y.append(y_test[i])
xtg_20=np.concatenate((xtg,np.array(x)),axis=0)
ytg_20=np.concatenate((ytg,np.array(y)),axis=0)

model = VGG16(include_top=False , weights="imagenet",input_shape=(128,128,3))

new_model = Sequential()
new_model.add(model)

#new_model.add(Dense(128,activation="relu"))
#new_model.add(Dropout(0.4))

new_model.add(tf.keras.layers.AveragePooling2D())
new_model.add(Flatten())

new_model.add(Dense(1024,activation="relu"))
new_model.add(Dropout(0.4))

new_model.add(Dense(64,activation="relu"))
new_model.add(Dropout(0.5))


#new_model.add(Dense(128,activation="relu"))
new_model.add(Dense(2, activation="sigmoid"))

model.summary()
opt = Adam(lr=0.00001)
new_model.compile(optimizer = opt , loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), 
              metrics = ['accuracy'])
new_model.fit(x_train,y_train, epochs=25, batch_size=10)

def confusion_Roc(model,samples,label):
    predictions = model.predict_classes(samples)
    print(classification_report(label, predictions, target_names = ['Non-COVID(Class 0)','COVID (Class 1)']))
    predict_label = model.predict(samples)  
    fpr, tpr, thresholds = roc_curve(label,predict_label[ : ,1])
    roc_auc = auc(fpr, tpr)
    display = RocCurveDisplay(fpr=fpr, tpr=tpr, roc_auc=roc_auc, estimator_name='example estimator')
    display.plot()  
    plt.show()

eva_test=new_model.evaluate(x_test,y_test, verbose=0)
confusion_Roc(new_model,x_test,y_test)
print('The accuracy of test samples is : ',eva_test[1]*100,'%')

new_model.save('/content/drive/MyDrive/generated/ConvNet3')

